import React, { createContext, useContext, useState } from 'react';

const T = {
  en: {
    appName: 'CivicRedress',
    tagline: 'Smart Governance',
    goodDay: 'Good day,',
    newComplaint: 'New Complaint',
    trackId: 'Enter Application ID to track...',
    track: 'Track',
    total: 'Total',
    underReview: 'Under Review',
    inProgress: 'In Progress',
    resolved: 'Resolved',
    all: 'All',
    active: 'Active',
    saved: 'Saved',
    noComplaints: 'No complaints here',
    fileFirst: 'Report a civic issue and track its resolution',
    fileComplaint: 'File a Complaint',
    appId: 'Application ID',
    save: 'Save',
    follow: 'Follow',
    following: 'Following',
    qr: 'QR',
    trackBtn: 'Track →',
    scanToTrack: 'Scan to track this complaint',
    close: 'Close',
    uploadPhoto: 'Upload Photo',
    uploadHint: 'Take or upload a photo — AI will detect the issue',
    whatIssue: "What's the issue?",
    issuePlaceholder: 'e.g. Broken streetlight on MG Road',
    location: 'Location',
    locationPlaceholder: 'Street, Area',
    pincode: 'Pincode',
    aiAnalyzing: 'AI is analyzing...',
    aiDetected: 'AI detected:',
    confidence: 'confidence',
    next: 'Next →',
    submit: 'Submit Complaint',
    submitting: 'Submitting...',
    submitted: 'Submitted',
    assignedStatus: 'Assigned',
    underReviewStatus: 'Under Review',
    inProgressStatus: 'In Progress',
    resolvedStatus: 'Resolved',
    closedStatus: 'Closed',
    rejectedStatus: 'Rejected',
    escalatedStatus: 'Escalated',
    progress: 'Progress',
    aiClassification: 'AI Classification',
    statusTimeline: 'Status Timeline',
    comments: 'Comments',
    addComment: 'Add a comment...',
    post: 'Post',
    rateResolution: 'Rate Resolution',
    giveFeedback: 'Give Feedback',
    cancel: 'Cancel',
    howResolution: 'How was the resolution?',
    official: 'Official',
    noUpdates: 'No updates yet',
    complaintNotFound: 'Complaint not found',
    backDashboard: '← Dashboard',
    locationNotSpecified: 'Location not specified',
    tapToChange: 'Tap to change',
    step1: 'Photo & Details',
    step2: 'Review & Submit',
    aiAutoDetect: 'AI auto-detects the issue from your photo',
    summaryTitle: 'Complaint Summary',
    issue: 'Issue',
    category: 'Category',
    photo: 'Photo',
    attached: 'attached',
    none: 'None',
    resolution: 'Resolution',
    rejectionReason: 'Rejection Reason',
    citizenFeedback: 'Citizen Feedback',
    filed: 'Filed',
    changePhoto: 'Change Photo',
  },
  kn: {
    appName: 'ನಾಗರಿಕ ಪರಿಹಾರ',
    tagline: 'ಸ್ಮಾರ್ಟ್ ಆಡಳಿತ',
    goodDay: 'ಶುಭ ದಿನ,',
    newComplaint: 'ಹೊಸ ದೂರು',
    trackId: 'ಅರ್ಜಿ ID ನಮೂದಿಸಿ...',
    track: 'ಟ್ರ್ಯಾಕ್',
    total: 'ಒಟ್ಟು',
    underReview: 'ಪರಿಶೀಲನೆಯಲ್ಲಿ',
    inProgress: 'ಪ್ರಗತಿಯಲ್ಲಿ',
    resolved: 'ಪರಿಹರಿಸಲಾಗಿದೆ',
    all: 'ಎಲ್ಲಾ',
    active: 'ಸಕ್ರಿಯ',
    saved: 'ಉಳಿಸಿದ',
    noComplaints: 'ಇಲ್ಲಿ ದೂರುಗಳಿಲ್ಲ',
    fileFirst: 'ನಾಗರಿಕ ಸಮಸ್ಯೆ ವರದಿ ಮಾಡಿ',
    fileComplaint: 'ದೂರು ಸಲ್ಲಿಸಿ',
    appId: 'ಅರ್ಜಿ ID',
    save: 'ಉಳಿಸಿ',
    follow: 'ಅನುಸರಿಸಿ',
    following: 'ಅನುಸರಿಸಲಾಗಿದೆ',
    qr: 'QR',
    trackBtn: 'ಟ್ರ್ಯಾಕ್ →',
    scanToTrack: 'ಟ್ರ್ಯಾಕ್ ಮಾಡಲು ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',
    close: 'ಮುಚ್ಚಿ',
    uploadPhoto: 'ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    uploadHint: 'ಫೋಟೋ ತೆಗೆಯಿರಿ — AI ಸಮಸ್ಯೆ ಪತ್ತೆ ಮಾಡುತ್ತದೆ',
    whatIssue: 'ಸಮಸ್ಯೆ ಏನು?',
    issuePlaceholder: 'ಉದಾ: ರಸ್ತೆ ದೀಪ ಕೆಟ್ಟಿದೆ',
    location: 'ಸ್ಥಳ',
    locationPlaceholder: 'ಬೀದಿ, ಪ್ರದೇಶ',
    pincode: 'ಪಿನ್‌ಕೋಡ್',
    aiAnalyzing: 'AI ವಿಶ್ಲೇಷಿಸುತ್ತಿದೆ...',
    aiDetected: 'AI ಪತ್ತೆ ಮಾಡಿದೆ:',
    confidence: 'ವಿಶ್ವಾಸ',
    next: 'ಮುಂದೆ →',
    submit: 'ದೂರು ಸಲ್ಲಿಸಿ',
    submitting: 'ಸಲ್ಲಿಸಲಾಗುತ್ತಿದೆ...',
    submitted: 'ಸಲ್ಲಿಸಲಾಗಿದೆ',
    assignedStatus: 'ನಿಯೋಜಿಸಲಾಗಿದೆ',
    underReviewStatus: 'ಪರಿಶೀಲನೆಯಲ್ಲಿ',
    inProgressStatus: 'ಪ್ರಗತಿಯಲ್ಲಿ',
    resolvedStatus: 'ಪರಿಹರಿಸಲಾಗಿದೆ',
    closedStatus: 'ಮುಚ್ಚಲಾಗಿದೆ',
    rejectedStatus: 'ತಿರಸ್ಕರಿಸಲಾಗಿದೆ',
    escalatedStatus: 'ಎಸ್ಕಲೇಟ್ ಮಾಡಲಾಗಿದೆ',
    progress: 'ಪ್ರಗತಿ',
    aiClassification: 'AI ವರ್ಗೀಕರಣ',
    statusTimeline: 'ಸ್ಥಿತಿ ಟೈಮ್‌ಲೈನ್',
    comments: 'ಕಾಮೆಂಟ್‌ಗಳು',
    addComment: 'ಕಾಮೆಂಟ್ ಸೇರಿಸಿ...',
    post: 'ಪೋಸ್ಟ್',
    rateResolution: 'ಪರಿಹಾರ ರೇಟ್ ಮಾಡಿ',
    giveFeedback: 'ಪ್ರತಿಕ್ರಿಯೆ ನೀಡಿ',
    cancel: 'ರದ್ದು',
    howResolution: 'ಪರಿಹಾರ ಹೇಗಿತ್ತು?',
    official: 'ಅಧಿಕೃತ',
    noUpdates: 'ಇನ್ನೂ ಅಪ್‌ಡೇಟ್‌ಗಳಿಲ್ಲ',
    complaintNotFound: 'ದೂರು ಕಂಡುಬಂದಿಲ್ಲ',
    backDashboard: '← ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    locationNotSpecified: 'ಸ್ಥಳ ನಿರ್ದಿಷ್ಟಪಡಿಸಿಲ್ಲ',
    tapToChange: 'ಬದಲಾಯಿಸಲು ಟ್ಯಾಪ್ ಮಾಡಿ',
    step1: 'ಫೋಟೋ & ವಿವರ',
    step2: 'ಪರಿಶೀಲಿಸಿ & ಸಲ್ಲಿಸಿ',
    aiAutoDetect: 'AI ಫೋಟೋದಿಂದ ಸಮಸ್ಯೆ ಪತ್ತೆ ಮಾಡುತ್ತದೆ',
    summaryTitle: 'ದೂರು ಸಾರಾಂಶ',
    issue: 'ಸಮಸ್ಯೆ',
    category: 'ವರ್ಗ',
    photo: 'ಫೋಟೋ',
    attached: 'ಲಗತ್ತಿಸಲಾಗಿದೆ',
    none: 'ಇಲ್ಲ',
    resolution: 'ಪರಿಹಾರ',
    rejectionReason: 'ತಿರಸ್ಕಾರ ಕಾರಣ',
    citizenFeedback: 'ನಾಗರಿಕ ಪ್ರತಿಕ್ರಿಯೆ',
    filed: 'ಸಲ್ಲಿಸಲಾಗಿದೆ',
    changePhoto: 'ಫೋಟೋ ಬದಲಾಯಿಸಿ',
  },
  hi: {
    appName: 'नागरिक समाधान',
    tagline: 'स्मार्ट शासन',
    goodDay: 'नमस्ते,',
    newComplaint: 'नई शिकायत',
    trackId: 'आवेदन ID दर्ज करें...',
    track: 'ट्रैक',
    total: 'कुल',
    underReview: 'समीक्षाधीन',
    inProgress: 'प्रगति में',
    resolved: 'हल हुआ',
    all: 'सभी',
    active: 'सक्रिय',
    saved: 'सहेजा',
    noComplaints: 'यहाँ कोई शिकायत नहीं',
    fileFirst: 'नागरिक समस्या रिपोर्ट करें',
    fileComplaint: 'शिकायत दर्ज करें',
    appId: 'आवेदन ID',
    save: 'सहेजें',
    follow: 'फॉलो',
    following: 'फॉलो किया',
    qr: 'QR',
    trackBtn: 'ट्रैक →',
    scanToTrack: 'ट्रैक करने के लिए स्कैन करें',
    close: 'बंद करें',
    uploadPhoto: 'फ़ोटो अपलोड करें',
    uploadHint: 'फ़ोटो लें — AI समस्या पहचानेगा',
    whatIssue: 'समस्या क्या है?',
    issuePlaceholder: 'जैसे: सड़क की बत्ती खराब है',
    location: 'स्थान',
    locationPlaceholder: 'गली, क्षेत्र',
    pincode: 'पिनकोड',
    aiAnalyzing: 'AI विश्लेषण कर रहा है...',
    aiDetected: 'AI ने पहचाना:',
    confidence: 'विश्वास',
    next: 'अगला →',
    submit: 'शिकायत दर्ज करें',
    submitting: 'दर्ज हो रहा है...',
    submitted: 'दर्ज किया',
    assignedStatus: 'सौंपा गया',
    underReviewStatus: 'समीक्षाधीन',
    inProgressStatus: 'प्रगति में',
    resolvedStatus: 'हल हुआ',
    closedStatus: 'बंद',
    rejectedStatus: 'अस्वीकृत',
    escalatedStatus: 'एस्केलेट किया',
    progress: 'प्रगति',
    aiClassification: 'AI वर्गीकरण',
    statusTimeline: 'स्थिति टाइमलाइन',
    comments: 'टिप्पणियाँ',
    addComment: 'टिप्पणी जोड़ें...',
    post: 'पोस्ट',
    rateResolution: 'समाधान रेट करें',
    giveFeedback: 'प्रतिक्रिया दें',
    cancel: 'रद्द करें',
    howResolution: 'समाधान कैसा था?',
    official: 'आधिकारिक',
    noUpdates: 'अभी कोई अपडेट नहीं',
    complaintNotFound: 'शिकायत नहीं मिली',
    backDashboard: '← डैशबोर्ड',
    locationNotSpecified: 'स्थान निर्दिष्ट नहीं',
    tapToChange: 'बदलने के लिए टैप करें',
    step1: 'फ़ोटो & विवरण',
    step2: 'समीक्षा & दर्ज करें',
    aiAutoDetect: 'AI फ़ोटो से समस्या पहचानता है',
    summaryTitle: 'शिकायत सारांश',
    issue: 'समस्या',
    category: 'श्रेणी',
    photo: 'फ़ोटो',
    attached: 'संलग्न',
    none: 'कोई नहीं',
    resolution: 'समाधान',
    rejectionReason: 'अस्वीकृति कारण',
    citizenFeedback: 'नागरिक प्रतिक्रिया',
    filed: 'दर्ज किया',
    changePhoto: 'फ़ोटो बदलें',
  },
};

const LangContext = createContext();
export const useLang = () => useContext(LangContext);

export function LangProvider({ children }) {
  const [lang, setLang] = useState(localStorage.getItem('lang') || 'en');
  const t = (key) => T[lang]?.[key] || T.en[key] || key;
  const changeLang = (l) => { setLang(l); localStorage.setItem('lang', l); };
  return (
    <LangContext.Provider value={{ lang, changeLang, t }}>
      {children}
    </LangContext.Provider>
  );
}
